#
# Copyright (c) 2019 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

zuul:
  routes:
    node-composer:
      path: /redfish/v1/Nodes/**
      strip-prefix: false
      serviceId: NODE-COMPOSER
    event-service:
      path: /redfish/v1/EventService/**
      strip-prefix: false
      serviceId: EVENT-SERVICE
    session-service:
      path: /redfish/v1/SessionService/**
      strip-prefix: false
      serviceId: AAA-SERVICE
    account-service:
      path: /redfish/v1/AccountService/**
      strip-prefix: false
      serviceId: AAA-SERVICE
    resource-manager:
      path: /redfish/v1/**
      strip-prefix: false
      serviceId: RESOURCE-MANAGER:PSME
  retryable: true
  ignoredPatterns: /redfish/v1/EventService/Events/**
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
        - health
        - configprops
        - env
        - loggers
        - logfile
        - httptrace
        - threaddump
        - routes
        - filters
        - prometheus
server:
  port: 8080
  httpsPort: 8443
  ssl:
    enabled: false

RESOURCE-MANAGER:PSME:
  ribbon:
    ReadTimeout: 100000

SERVICE-DETECTOR:
  ribbon:
    ReadTimeout: 100000

NODE-COMPOSER:
  ribbon:
    ReadTimeout: 3000000

access-verification-provider:
  service-id: AAA-SERVICE