apiVersion: v1
kind: Service
metadata:
  name: {{ template "podm-gateway.fullname" . }}
  labels:
    app: {{ template "podm-gateway.name" . }}
    chart: {{ template "podm-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.global.northbound_security.enabled  }}
    - port: {{ .Values.service.httpsPort }}
      name: https
      targetPort: https
    {{ else }}
    - port: {{ .Values.service.port }}
      name: http
      targetPort: http
    {{ end }}
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: 30000
      {{ end }}
      protocol: TCP
  selector:
    app: {{ template "podm-gateway.name" . }}
    release: {{ .Release.Name }}
