---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
  name: {{ .Values.secretName }}
  namespace: default
type: Opaque
data:
  database-password: {{ include "database.password" . | b64enc | quote }}
