apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "service-registry.fullname" . }}
  labels:
    app: {{ template "service-registry.name" . }}
    chart: {{ template "service-registry.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "service-registry.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/scrape: "true"
      labels:
        app: {{ template "service-registry.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- if ne .Values.global.registry_secret "" }}
      imagePullSecrets:
        - name: {{ .Values.global.registry_secret }}{{ end }}
      volumes:
      {{- include "shared.coverage.volume" . | indent 8}}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8761
              protocol: TCP
          volumeMounts:
          {{- include "shared.coverage.mount" . | indent 12}}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
